---
title: "Untitled"
output: html_document
date: "2023-07-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
df <- read_delim("politbarometer_zeitreihe.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

```


```{r}
df$date <- paste0(substring(df$...2, 7,11),"-",substring(df$...2,4,5))




df$`Energie/Versorgung/Klima`

df$Coronavirus

df$`Ausländer/Integration/Flüchtlinge`




  
```


```{r}
dfGroup <- df%>%
  select(`Energie/Versorgung/Klima`,Coronavirus,`Ausländer/Integration/Flüchtlinge`, date)%>%
  group_by(date)%>%
  reframe(
    Flüchtlinge = sum(`Ausländer/Integration/Flüchtlinge`),
    Klima = sum(`Energie/Versorgung/Klima`),
    Corona = sum(Coronavirus),
    Total = sum(Coronavirus) + sum(`Energie/Versorgung/Klima`) +sum(`Ausländer/Integration/Flüchtlinge`) 
  )
```



```{r}
dfMelt <- reshape2::melt(dfGroup, id.vars = "date")



ggplot(dfMelt, aes(x = date, y =value, group = variable, color = variable))+
         geom_line()+
         theme_bw()+
         theme(axis.text.x = element_text(angle = 180))
       
```

